version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: "python app.py"
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: "npm run serve"
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # environment:
    #   - npm_config_unsafe_perm=true
